### ISSUE TITLE
doubt regarding mpi_scatter

### ISSUE THREAD

**Issue by rahulnagurtha** [wesleykendall/mpitutorial#29]
In line number 69 corresponding to [this](https://github.com/wesleykendall/mpitutorial/blob/gh-pages/tutorials/mpi-scatter-gather-and-allgather/code/avg.c) code, aren't we scattering the data multiple times(which is just a waste of time) from every process ? My doubt is that, if we make the mpi_scatter call from just one process(say process numbered 0), can't we achieve the same result and thereby save time ? Thanks !

**Comment by wesleykendall** [comment]
All processes have to call mpi_scatter at the same time, otherwise they won't be able to coordinate scattering of data

**Comment by rahulnagurtha** [comment]
Do you mean to say that the call is equivalent to ,

mpi_barrier()
mpi_scatter()
mpi_barrier()

?

**Comment by wesleykendall** [comment]
Yes! Exactly. When using scatter or gather (or any blocking collective communication), processes must all coordinate at once to perform it
