### ISSUE TITLE
Exclusive terminology in MPI tutorials

### ISSUE THREAD

**Issue by janderudder** [wesleykendall/mpitutorial#57]
Hello

### Context 

Recently there's been debate about specific computer science terminology referring to racial discrimination to convey meaning. Following this debate, the Linux kernel project adopted style guidelines advising the use of inclusive terminology, consisting essentially in not introducing non-inclusive words in new code. Although it is always possible to go and replace words in already established source.

Below is an excerpt from a commit by Dan Williams titled `CodingStyle: Inclusive Terminology` [Github/Torvalds/linux/Documentation/process/coding-style.rst](https://github.com/torvalds/linux/blob/master/Documentation/process/coding-style.rst).

> For symbol names and documentation, avoid introducing new usage of 'master / slave' (or 'slave' independent of 'master') and > 'blacklist / whitelist'.
>
> Recommended replacements for 'master / slave' are:
> '{primary,main} / {secondary,replica,subordinate}' '{initiator,requester} / {target,responder}' '{controller,host} / {device,worker,proxy}' 'leader / follower' 'director / performer'
>
> Recommended replacements for 'blacklist/whitelist' are:
> 'denylist / allowlist' 'blocklist / passlist'

Here is [a link to the discussion](https://lore.kernel.org/ksummit-discuss/159389297140.2210796.13590142254668787525.stgit@dwillia2-desk3.amr.corp.intel.com/) about this patch to the coding style guide, giving explanation and arguments in favor of these changes.

### Exclusive language in MPI tutorials

I noticed MPI tutorials make several uses of exclusive language.
Below are presented the results of "master" and "slave" words search, done from this repository's root directory.

```
$ grep -irso 'master' ./tutorials | wc -l
27

$ grep -irso 'slave' ./tutorials | wc -l
18
```

My intent with this post is to raise awareness of this topic, in the hope that you find this an issue worth solving.
I wish you happy and creative coding.

**Comment by wesbland** [comment]
That's a good point. Many of the projects I've been involved with lately have been making these kinds of changes and we should do so here as well. I'll see about making a quick pass here to improve things.

**Comment by wesbland** [comment]
Before I merge the change in #58 , I do want to get a little clarification from those who helped with the translations. Once I'm sure those are correct, I'll bring the PR in.
