### ISSUE TITLE
Slot issue for mpi-broadcast-and-collective-communication

### ISSUE THREAD

**Issue by Rubix982** [wesleykendall/mpitutorial#77]
Hi!

I love the project and the work gone into this.
I was trying out the tutorials/, when I ran into this weird little issue. I'm not sure how to solve this.

If I run, `./run.py compare_bcast` the following command runs,
```
mpirun -n 16  ./mpi-broadcast-and-collective-communication/code/compare_bcast 100000 10
```

The error is,
> --------------------------------------------------------------------------
> There are not enough slots available in the system to satisfy the 16
> slots that were requested by the application:
>
> ./mpi-broadcast-and-collective-communication/code/compare_bcast
>
> Either request fewer slots for your application, or make more slots
> available for use.
> 
> A "slot" is the Open MPI term for an allocatable unit where we can
> launch a process.  The number of slots available are defined by the
> environment in which Open MPI processes are run:
>
>  1. Hostfile, via "slots=N" clauses (N defaults to number of
>     processor cores if not provided)
>  2. The --host command line parameter, via a ":N" suffix on the
>     hostname (N defaults to 1 if not provided)
>  3. Resource manager (e.g., SLURM, PBS/Torque, LSF, etc.)
>  4. If none of a hostfile, the --host command line parameter, or an
>     RM is present, Open MPI defaults to the number of processor cores
>
> In all the above cases, if you want Open MPI to default to the number
> of hardware threads instead of the number of processor cores, use the
> --use-hwthread-cpus option.
> 
> Alternatively, you can use the --oversubscribe option to ignore the
> number of available slots when deciding the number of processes to
> launch.

Clearly, the `16` above is causing the issue. Whereas running `./run.py my_bcast` runs my_bcast with 4 processes, so there is a slight modification needed in `run.py`, but I'm not sure what to exactly change. 

My machine specifications are as follows,
```
Operating System: Kubuntu 20.04
Kernel Version: 5.4.0-58-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-8665U CPU @ 1.90GHz
Memory: 15.5 GiB of RAM
```

**Comment by wesbland** [comment]
This is something to do with the way the Open MPI launcher (PRRTE) determines how many process can be run on your machine. I would recommend asking the Open MPI community on their mailing list for some help here:

https://www.open-mpi.org/community/lists/ompi.php
