### ISSUE TITLE
incorrect book recommendation?

### ISSUE THREAD

**Issue by rscohn2** [wesleykendall/mpitutorial#87]
I wanted a tutorial-style book that covered RMA, and bought this one:

https://github.com/mpitutorial/mpitutorial/blob/gh-pages/recommended-books.md#using-mpi---3rd-edition

It doesn't cover RMA. Did he mean to recommend: https://www.amazon.com/Using-Advanced-MPI-Message-Passing-Engineering/dp/0262527634/ref=sr_1_1?keywords=using+advanced+mpi&qid=1637681415&qsid=144-8909898-5641728&s=books&sr=1-1&sres=0262527634%2C0262571331%2CB07JJY4Z8D&srpt=ABIS_BOOK ?

I guess the book is out of print and copies are very expensive. Is there something else?

**Comment by wesbland** [comment]
You may be right here that the "regular" edition doesn't cover RMA. I'm a little surprised to hear that it doesn't, given that RMA was such a big part of MPI 3.0. If you want to be sure about the advanced version, contact me offline. We both know people who have the that book who could check.

Once we get this figured out, I can update the website.

**Comment by wesbland** [comment]
Just found the TOC on the website from the authors at Argonne: https://www.mcs.anl.gov/research/projects/mpi/usingmpi/

Looks like the Advanced version is the one that has a chapter on RMA. If you really want a print copy, there may be one owned by our employer in town that we could pass your way.
