### ISSUE TITLE
Possible typo in article Installing MPICH2

### ISSUE THREAD

**Issue by lewisgross1296** [wesleykendall/mpitutorial#93]
I have started going through these tutorials, and I think I noticed a mistake in one of the commands on this [page](https://mpitutorial.com/tutorials/installing-mpich2/). Under the section `Installing MPICH`, the command for unpacking the tar for MPICH v3.3.2 is given as 
```
tar -xzf mpich3-3.2.tar.gz
```
However, when I `wget` the tar file from [their downloads page](https://www.mpich.org/static/downloads/3.3.2/mpich-3.3.2.tar.gz), the zip file is named `mpich-3.3.2.tar.gz`. It is slightly different, so I figured I would submit an issue. Should be a very quick fix if this is intended to match the MPICH from the distributor.

**Comment by wesbland** [comment]
Thanks. I've taken care of this with 0a724d5c94f5522bbbd2f018bb23773906349005.

**Comment by lewisgross1296** [comment]
I think you changed it to `mpich-3-3.2`, but it is `mpich-3.3.2`. Two dots, not two dashes.
